/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ClienteBean;
import dao.ClienteDao;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Guilherme Henrique Bialas(guilhermebialas31@gmail.com)
 */
public class CadastroCliente extends javax.swing.JFrame {

    private ArrayList<JLabel> jLabels = new ArrayList();

    /**
     * Creates new form CadstroCliente
     */
    public CadastroCliente() {
        initComponents();
        acaoBotaoAdicionar();
        mascaraCpf();
        mascaraCnpj();
        mascaraCep();
        mascarTelefone();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelTelefome = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabelCpf = new javax.swing.JLabel();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jLabelCnpj = new javax.swing.JLabel();
        jFormattedTextFieldCnpj = new javax.swing.JFormattedTextField();
        jLabelCep = new javax.swing.JLabel();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();

        jTextField8.setText("jTextField8");

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Cliente");
        setResizable(false);

        jLabelNome.setText("Nome :");

        jLabelTelefome.setText("Telefone :");

        jLabelCpf.setText("Cpf :");

        jLabelCnpj.setText("Cnpj :");

        jLabelCep.setText("Cep :");

        jLabelBairro.setText("Bairro :");

        jLabelEndereco.setText("Endereço :");

        jLabelCidade.setText("Cidade :");

        jLabelNumero.setText("Número :");

        jLabel6.setText("E-mail :");

        jButton2.setText("Sair");

        jButton4.setText("Alterar");

        jButtonAdicionar.setText("Adicionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTelefome)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCnpj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jLabelEndereco)
                            .addComponent(jLabelBairro)
                            .addComponent(jTextFieldEndereco)
                            .addComponent(jTextFieldBairro)
                            .addComponent(jTextFieldCidade)
                            .addComponent(jLabelNumero)
                            .addComponent(jTextFieldNumero)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefome)
                    .addComponent(jLabelEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpf)
                    .addComponent(jLabelCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCnpj)
                    .addComponent(jLabelNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCep)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    public void validacao() {
        //Nome
        if (jTextFieldNome.getText().isEmpty()) {
            gerarJLabel("Deve preencher.", jTextFieldNome);
            bordaErro(jTextFieldNome);
            jTextFieldNome.requestFocus();
        } else if (jTextFieldNome.getText().length() < 2) {
            gerarJLabel("Nome inválido", jTextFieldNome);
            bordaErro(jTextFieldNome);
            jTextFieldNome.requestFocus();
        } else {
            bordaSucesso(jTextFieldNome);

        }

        //Email
        if (jTextFieldEmail.getText().isEmpty()) {
            gerarJLabel("Deve preencher.", jTextFieldEmail);
            bordaErro(jTextFieldEmail);
            jTextFieldEmail.requestFocus();
        } else if (jTextFieldEmail.getText().length() < 2) {
            gerarJLabel("Email inválido", jTextFieldEmail);
            bordaErro(jTextFieldEmail);
            jTextFieldEmail.requestFocus();
        } else {
            bordaSucesso(jTextFieldEmail);

        }

        //Bairro
        if (jTextFieldBairro.getText().isEmpty()) {
            gerarJLabel("Deve preencher.", jTextFieldBairro);
            bordaErro(jTextFieldBairro);
            jTextFieldBairro.requestFocus();
        } else if (jTextFieldBairro.getText().length() < 2) {
            gerarJLabel("Bairro não existe", jTextFieldBairro);
            bordaErro(jTextFieldBairro);
            jTextFieldBairro.requestFocus();
        } else {
            bordaSucesso(jTextFieldBairro);

        }

        //Enderço
        if (jTextFieldEndereco.getText().isEmpty()) {
            gerarJLabel("Deve preencher.", jTextFieldEndereco);
            bordaErro(jTextFieldEndereco);
            jTextFieldEndereco.requestFocus();
        } else if (jTextFieldEndereco.getText().length() < 2) {
            gerarJLabel("Endereço não existe", jTextFieldEndereco);
            bordaErro(jTextFieldEndereco);
            jTextFieldEndereco.requestFocus();
        } else {
            bordaSucesso(jTextFieldEndereco);

        }

        //Cidade
        if (jTextFieldCidade.getText().isEmpty()) {
            gerarJLabel("Deve preencher.", jTextFieldCidade);
            bordaErro(jTextFieldCidade);
            jTextFieldCidade.requestFocus();
        } else if (jTextFieldCidade.getText().length() < 2) {
            gerarJLabel("Cidade não existe", jTextFieldCidade);
            bordaErro(jTextFieldCidade);
            jTextFieldCidade.requestFocus();
        } else {
            bordaSucesso(jTextFieldCidade);

        }
        //Numero
        if (jTextFieldNumero.getText().isEmpty()) {
            gerarJLabel("Deve preencher.", jTextFieldNumero);
            bordaErro(jTextFieldNumero);
            jTextFieldNumero.requestFocus();
        } else {
            try {
                if (Float.parseFloat(jTextFieldNumero.getText()) < 0) {
                    gerarJLabel("Número inválido", jTextFieldNumero);
                    bordaErro(jTextFieldNumero);
                    jTextFieldNumero.requestFocus();
                }
            } catch (Exception e) {
                gerarJLabel("Não pode conter letras", jTextFieldNumero);
                bordaErro(jTextFieldNumero);
            }
            bordaSucesso(jTextFieldNumero);
        }
    }

    public void mascaraCpf() {
        try {
            MaskFormatter maskFormatter = new MaskFormatter("###.###.###-##");
            maskFormatter.install(jFormattedTextFieldCpf);
        } catch (Exception e) {
            if (jFormattedTextFieldCpf.getText().length() < 11) {
                gerarJLabelMask("Cpf inválido", jFormattedTextFieldCpf);
                
                jFormattedTextFieldCpf.requestFocus();
            } else {

            }
        }
    }

    public void mascaraCnpj() {
        try {
            MaskFormatter maskFormatter = new MaskFormatter("##.###./####-##");
            maskFormatter.install(jFormattedTextFieldCnpj);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Chame o prog");
        }
    }

    public void mascaraCep() {
        try {
            MaskFormatter maskFormatter = new MaskFormatter("#####-###");
            maskFormatter.install(jFormattedTextFieldCep);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Chame o prog");
        }
    }

    public void acaoBotaoAdicionar() {
        jButtonAdicionar.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                validacao();
                salvarBanco();
                limparCampos();
                JOptionPane.showMessageDialog(null, "Clinte cadastrado com sucesso");

            }
        });

    }

    public void mascarTelefone() {
        try {
            MaskFormatter maskFormatter = new MaskFormatter("(##)####-####");
            maskFormatter.install(jFormattedTextFieldTelefone);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Chame o prog");
        }

    }

    public void limparCampos() {
        jTextFieldNome.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldEmail.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNumero.setText("");
        jFormattedTextFieldCep.setText("");
        jFormattedTextFieldCnpj.setText("");
        jFormattedTextFieldCpf.setText("");
        jFormattedTextFieldTelefone.setText("");

    }

    public void salvarBanco() {
        ClienteBean cliente = new ClienteBean();
        cliente.setNome(jTextFieldNome.getText().trim().replace(".", "").replace(",", "").replace("/", "").replace("*", ""));
        cliente.setTelefone(jFormattedTextFieldTelefone.getText());
        cliente.setCpf(jFormattedTextFieldCpf.getText());
        cliente.setNumero(Integer.parseInt(jTextFieldNumero.getText().trim().replace(".", "").replace(",", "").replace("/", "").replace("*", "")));
        cliente.setEndereco(jTextFieldEndereco.getText().trim().replace(".", "").replace(",", "").replace("/", "").replace("*", ""));
        cliente.setCpf(jFormattedTextFieldCpf.getText());
        cliente.setCep(jFormattedTextFieldCep.getText());
        cliente.setCnpj(jFormattedTextFieldCnpj.getText());
        cliente.setBairro(jTextFieldBairro.getText().trim().replace(".", "").replace(",", "").replace("/", "").replace("*", ""));
        cliente.setCidade(jTextFieldCidade.getText().trim().replace(".", "").replace(",", "").replace("/", "").replace("*", ""));
        cliente.setEmail(jTextFieldEmail.getText().trim().replace(".", "").replace(",", "").replace("/", "").replace("*", ""));
  new ClienteDao().inserir(produto);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldCnpj;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCnpj;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelTelefome;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables

    private void gerarJLabel(String texto, JTextField jTextField) {
        JLabel jLabelE = new JLabel();
        jLabelE.setText(texto);
        jLabelE.setForeground(Color.red);
        jLabelE.setLocation(jTextField.getX(), jTextField.getY() + jTextField.getHeight());
        jLabelE.setSize(jTextField.getWidth(), 20);
        add(jLabelE);
        jLabels.add(jLabelE);
    }

    private void bordaSucesso(JTextField jTextField) {
        Border borda = BorderFactory.createLineBorder(Color.decode("#09e83d"), 1);
        jTextField.setBorder(borda);

    }

    private void bordaErro(JTextField jTextField) {
        Border borda = BorderFactory.createLineBorder(Color.red, 1);
        jTextField.setBorder(borda);

    }

    private void gerarJLabelMask(String texto, JFormattedTextField JFormattedTextField) {
        JLabel jLabelE = new JLabel();
        jLabelE.setText(texto);
        jLabelE.setForeground(Color.red);
        jLabelE.setLocation(JFormattedTextField.getX(), JFormattedTextField.getY() + JFormattedTextField.getHeight());
        jLabelE.setSize(JFormattedTextField.getWidth(), 20);
        add(jLabelE);
        jLabels.add(jLabelE);
    }

    private void bordaErroMask(JFormattedTextField JFormattedTextField) {
        Border borda = BorderFactory.createLineBorder(Color.red, 1);
        JFormattedTextField.setBorder(borda);
    }
private void bordaSucessoMask(JFormattedTextField JFormattedTextField){
       Border borda = BorderFactory.createLineBorder(Color.decode("#09e83d"), 1);
        JFormattedTextField.setBorder(borda);
}
}
